module.exports = {
    STATUS_RESPONSE_SUCCESS: 200,
    STATUS_RESPONSE_FAILED: 500,
    STATUS_RESPONSE_UNAUTHORIZED: 401,
    STATUS_RESPONSE_INVALIDSCHEMA: 422,
    STATUS_RESPONSE_FORBIDDEN: 403,
    STATUS_RESPONSE_NOTFOUND: 404,
}