export const STATUS_RESPONSE_SUCCESS = 200
export const STATUS_RESPONSE_FAILED = 500
export const STATUS_RESPONSE_UNAUTHORIZED = 401
export const STATUS_RESPONSE_INVALIDSCHEMA = 422
export const STATUS_RESPONSE_FORBIDDEN = 403
export const STATUS_RESPONSE_NOTFOUND = 404